### ISSUE TITLE
Incompatible Java versions

### ISSUE THREAD

**Issue by BethDevJS** [MultiEgg/Meta#6]
### Checklist

- [X] I have read and agree to the README (found on https://github.com/MultiEgg/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

### Current Behavior?

Currently there’s are some versions on the selectors that are using the incorrect version of Java for their version

### What should happen?

They should change to the correct version of Java but it gives up and exits causing a loop of failed installs

### Reproduction Steps

Current versions know to have this issue:
Purpur 1.14.4, 1.15.2, 1.16.5 

### Server Information

Latest?
Ubuntu 22.04
Prod

**Comment by expxx** [comment]
Will look into it.

**Comment by expxx** [comment]
We've patched this in the next public release.
